version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies...
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

  build:
    commands:
      - echo Building the Java application...
      - mvn package

artifacts:
  files:
    - target/*.jar
  name: MyJavaApp
